[build]
builder = "nixpacks"
buildCommand = "npm install && npm run build"

[deploy]
startCommand = "npx serve dist"
healthcheckPath = "/"
healthcheckTimeout = 180
healthcheckInterval = 15

[deploy.envs]
NODE_ENV = "production"
PORT = "3000" 