services:
  portfolio-frontend:
    image: andreusimus3/portfolio-frontend:latest
    ports:
      - "5173:80"
    depends_on:
      - portfolio-backend
    environment:
      - NODE_ENV=production
      - DOCKER_ENV='true'
    healthcheck:
      test: ["CMD", "wget", "--spider", "http://localhost:80"]
      interval: 30s
      timeout: 10s
      retries: 3
    restart: always
    networks:
      - portfolio-network
    expose:
      - "80"

  portfolio-backend:
    image: andreusimus3/portfolio-backend:latest
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - PORT=3000
      - CORS_ORIGIN=${FRONTEND_URL:-https://portfolio-frontend}
    healthcheck:
      test: ["CMD", "wget", "--spider", "http://localhost:3000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
    restart: always
    networks:
      - portfolio-network
    expose:
      - "3000"

  nginx:
    image: andreusimus3/portfolio-nginx:latest
    ports:
      - "8080:80"
    environment:
      - API_URL=${API_URL:-http://portfolio-backend:3000}
      - CLIENT_URL=${CLIENT_URL:-http://portfolio-frontend:5173}
      - NGINX_HOST=localhost
      - NGINX_PORT=80
    depends_on:
      - portfolio-backend
      - portfolio-frontend
    networks:
      - portfolio-network
    restart: always

networks:
  portfolio-network:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.28.0.0/16

volumes:
  backend_data: 