services:
  portfolio-frontend:
    build:
      context: .
      dockerfile: Dockerfile
    image: portfolio-frontend
    ports:
      - "5173:80"
    depends_on:
      - portfolio-backend
    environment:
      - NODE_ENV=production
      - DOCKER_ENV='true'
    healthcheck:
      test: ["CMD", "wget", "--spider", "http://localhost:80"]
      interval: 30s
      timeout: 10s
      retries: 3
    restart: unless-stopped
    networks:
      - portfolio-network

  portfolio-backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    image: portfolio-backend
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - PORT=3000
      - CORS_ORIGIN=${FRONTEND_URL:-http://portfolio-frontend}
    healthcheck:
      test: ["CMD", "wget", "--spider", "http://localhost:3000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
    restart: unless-stopped
    networks:
      - portfolio-network

  nginx:
    build:
      context: .
      dockerfile: Dockerfile.nginx
    image: portfolio-nginx
    ports:
      - "80:80"
    environment:
      - API_URL=${API_URL:-http://portfolio-backend:3000}
      - CLIENT_URL=${CLIENT_URL:-http://portfolio-frontend:5173}
    depends_on:
      - portfolio-backend
      - portfolio-frontend
    networks:
      - portfolio-network

networks:
  portfolio-network:
    driver: bridge

volumes:
  backend_data: 