# Frontend Service
[frontend]
name = "portfolio-frontend"

[frontend.build]
builder = "DOCKERFILE"
dockerfilePath = "Dockerfile"
image = "andreusimus/portfolio-frontend:latest"

[frontend.deploy]
healthcheckPath = "/"
healthcheckTimeout = 180
healthcheckInterval = 15

[frontend.envs]
NODE_ENV = "production"
PORT = "3000"

# Backend Service
[backend]
name = "portfolio-backend"

[backend.build]
builder = "DOCKERFILE"
dockerfilePath = "backend/Dockerfile"
image = "andreusimus/portfolio-backend:latest"

[backend.deploy]
healthcheckPath = "/health"
healthcheckTimeout = 180
healthcheckInterval = 15

[backend.envs]
NODE_ENV = "production"
PORT = "3001" 