# Frontend Service
[frontend]
name = "portfolio-frontend"

[frontend.build]
builder = "DOCKERFILE"
dockerfilePath = "Dockerfile"
image = "andreusimus3/portfolio-frontend:latest"

[frontend.deploy]
healthcheckPath = "/"
healthcheckTimeout = 180
healthcheckInterval = 15

[frontend.envs]
NODE_ENV = "production"
PORT = "3000"

# Backend Service
[backend]
name = "portfolio-backend"

[backend.build]
builder = "DOCKERFILE"
dockerfilePath = "backend/Dockerfile"
image = "andreusimus3/portfolio-backend:latest"

[backend.deploy]
healthcheckPath = "/health"
healthcheckTimeout = 180
healthcheckInterval = 15

[backend.envs]
NODE_ENV = "production"
PORT = "3000"

# Nginx Service
[build]
builder = "DOCKERFILE"
dockerfilePath = "Dockerfile.nginx"

[deploy]
startCommand = "nginx -g 'daemon off;'"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[[services]]
name = "nginx"
internal_port = 80 