name: Build and Deploy

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Frontend
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/portfolio-frontend:latest

      - name: Deploy to Railway
    
        with:
          service: portfolio-frontend
          project: ${{ secrets.RAILWAY_PROJECT_ID }}
        run: |
          # Deploy backend
          RAILWAY_TOKEN=${{ secrets.RAILWAY_TOKEN }}  railway up --service=86571dba-42da-4006-8201-bf7080d1d103
          # RAILWAY_TOKEN=${{ secrets.RAILWAY_TOKEN }} railway project --project ${{ secrets.RAILWAY_PROJECT_ID }}
          # # RAILWAY_TOKEN=${{ secrets.RAILWAY_TOKEN }} railway service --service portfolio-backend
          # # RAILWAY_TOKEN=${{ secrets.RAILWAY_TOKEN }} railway up
          
          # # # Deploy frontend
          # # RAILWAY_TOKEN=${{ secrets.RAILWAY_TOKEN }} railway project --project ${{ secrets.RAILWAY_PROJECT_ID }}
          # # RAILWAY_TOKEN=${{ secrets.RAILWAY_TOKEN }} railway service --service portfolio-frontend
          # # RAILWAY_TOKEN=${{ secrets.RAILWAY_TOKEN }} railway up



