name: Build and Deploy

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # - name: Build and push Backend
      #   uses: docker/build-push-action@v5
      #   with:
      #     context: ./backend
      #     push: true
      #     tags: ${{ secrets.DOCKER_USERNAME }}/portfolio-backend:latest

      # - name: Build and push Frontend
      #   uses: docker/build-push-action@v5
      #   with:
      #     context: .
      #     push: true
      #     tags: ${{ secrets.DOCKER_USERNAME }}/portfolio-frontend:latest

      - name: Install Railway CLI
        run: npm install -g @railway/cli

      - name: Deploy to Railway
        env:
          RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}
        run: |
          
          # Link and deploy after login
          railway login --token ${{ secrets.RAILWAY_TOKEN }}
          railway link --project ${{ secrets.RAILWAY_PROJECT_ID }} --environment production --service portfolio-backend
          railway redeploy
          railway link --project ${{ secrets.RAILWAY_PROJECT_ID }} --environment production --service portfolio-frontend
          railway redeploy
          
          
