name: Deploy to Railway

on:
  push:
    branches: [main]  # or your default branch
  pull_request:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install Railway
        run: npm install -g @railway/cli

      - name: Login to Railway
        run: |
          railway login --browserless --token "$RAILWAY_TOKEN"
        env:
          RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}

      - name: Initialize Railway Project
        run: |
          railway init --name portfolio-feedback
        env:
          RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}

      - name: Install Dependencies
        run: |
          npm ci
          cd backend && npm ci

      - name: Build
        run: |
          npm run build
          cd backend && npm run build

      - name: Deploy to Railway
        run: railway up
        env:
          RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }} 